### ISSUE TITLE
Is there an alternative / short version for this?

### ISSUE THREAD

**Issue by ghost** [camenduru/stable-diffusion-webui-saturncloud#1]
Sorry for asking too much, but your code kind of complicated, and was trying to use ngrok and doesnt seem to be supported, just wondering if you can make it simpler, so that can be used for different model and perhaps ngrok support. Thank you!

**Comment by ghost** [comment]
Nevermind.

**Comment by camenduru** [comment]
Please check new "Jupyter Notebook Without Tunnel"
