### ISSUE TITLE
Readme Asset

### ISSUE THREAD

**Issue by camenduru** [camenduru/stable-diffusion-webui-saturncloud#3]
![Screenshot 2023-08-09 021455](https://github.com/camenduru/stable-diffusion-webui-saturncloud/assets/54370274/10e001b9-397c-45b6-851d-b4dc67612ee9)
![Screenshot 2023-08-09 021335](https://github.com/camenduru/stable-diffusion-webui-saturncloud/assets/54370274/51c35f0d-1f98-4227-b72a-03643edc1c4d)

**Comment by ghost** [comment]
Informed by the SaturnCloud official that they upgraded the free tier up to 150 hours, how's everyone?

![Screenshot 2023-08-17 193223](https://github.com/camenduru/stable-diffusion-webui-saturncloud/assets/52849704/d1432833-93f4-41ac-a8a0-474ea71fac38)
