### ISSUE TITLE
Warning: Account deactivation

### ISSUE THREAD

**Issue by ghost** [camenduru/stable-diffusion-webui-saturncloud#5]
Account just got deactivated while using stable diffusion for hours (Somehow the auto-shutoff didn't work as it should be).

Just informing everyone, don't be happy yet for having hundreds of hours of GPU compute, be careful with your usage. Sooner or later it'll be the same as Colab.

**Comment by camenduru** [comment]
oh no 😐

**Comment by ghost** [comment]
Update: SaturnCloud updated their validation procedure by submitting your LinkedIn to verify your identity. (Perhaps same as SageMaker, Kaggle etc by providing your mobile phone number for verification).

![image](https://github.com/camenduru/stable-diffusion-webui-saturncloud/assets/52849704/1d895f9f-40c9-4e95-ad57-618e8dc66114)

Note: Currently waiting their approval of provided LinkedIn account, further update will be given. Might still has a chance that by just providing LinkedIn account doesn't mean your account get activated again.

**Comment by hyf12053** [comment]
I also encountered the same problem. I didn't get a reply after sending LinkedIn. Did you solve it?

**Comment by ghost** [comment]
> I also encountered the same problem. I didn't get a reply after sending LinkedIn. Did you solve it?

There's a notice of when the customer service will be back, currently waiting 30 mins left before contacting them.

Its on the chat button on the bottom right, and there's "Send us a message", it'll show you when they'll be back/active to be contacted.

Hope this helps.

**Comment by hyf12053** [comment]
I tried to use another account to log in. When I finished creating Resources, the account was disabled. I wonder if it is my personal problem?

**Comment by ghost** [comment]
Bad News to everyone, SaturnCloud has officially disallowed Stable Diffusion on free hosting, and allowing it in pro hosting(paid service). Might as well use Kaggle or SageMaker at this point, This only one of the available options shared.

![image](https://github.com/camenduru/stable-diffusion-webui-saturncloud/assets/52849704/dbad30d7-eaf6-4d38-abbb-a043900eaf8d)

Good Luck with everyone.
